server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weather?useUniCode_true&useSSL=false&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  config:
    import: optional:file:.env[.properties]

weather-stack:
  api-url: http://api.weatherstack.com/current
  api-key: ${API_KEY:default}

resilience4j:
  ratelimiter:
    instances:
      basic:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 10s